fix CI on forks (#475)

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -29,7 +29,7 @@ jobs:
       run: |
         # Cache the dependency-installation image layer on GitHub Packages to speed up CI. Use a
         # year/month tag to ensure we do refresh them occasionally.
-        DOCKER_TAG="docker.pkg.github.com/chanzuckerberg/miniwdl/miniwdl_ci:$(date +%Y%m)"
+        DOCKER_TAG="docker.pkg.github.com/${GITHUB_REPOSITORY}/miniwdl_ci:$(date +%Y%m)"
         echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
         if docker pull "$DOCKER_TAG"; then
           docker build -t "$DOCKER_TAG" --cache-from "$DOCKER_TAG" .
@@ -37,7 +37,7 @@ jobs:
           docker build -t "$DOCKER_TAG" .
         fi
         if [ "${{ matrix.ci_target }}" == "ci_housekeeping" ]; then
-          docker push "$DOCKER_TAG"
+          docker push "$DOCKER_TAG" || true  # allow failure for third-party PRs
         fi
     - name: make ${{ matrix.ci_target }}
       run: |
